[deps]
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TropicalNumbers = "b3a74e9c-7526-4576-a4eb-79c0d4c32334"
